apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "import-demo-app"
  annotations:
    github.com/project-slug: KB-FMF
spec:
  type: service
  lifecycle: development
  owner: "group:default/unset-owner"    
